conduct_id: '20273'
confirmed_at: '2026-05-17 14:43:51'
fukuan_1: 813.0
fukuan_2: 407.0
fukuan_3: 0.0
fukuan_4: 0.0
fukuan_list:
- 813.0
- 407.0
product_cls: '2'
strip_card_1: '0'
strip_card_2: '2621'
strip_card_3: ''
strip_card_4: ''
strip_card_list:
- '0'
- '2621'
strip_count: 2
